#服务器端口号
#server.port=8088

#数据源
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://121.199.202.220:3306/qichebaoxian
#spring.datasource.username=user6
#spring.datasource.password=User123456


#别名定义
#mybatis.type-aliases-package=cn.gaoshu.pojo


#redis支持的5种存储类型:String(字符串),hash(哈希),list(列表),set(集合),zset(有序集合)
#整合redis第二步
#指定redis服务器的IP地址
#spring.redis.host=192.168.222.33
#指定redis服务器的端口号
#spring.redis.port=6379



#配置FreeMarker
#开启缓存，开发阶段建议关闭
#spring.freemarker.cache=false
#spring.freemarker.charset=utf-8
#spring.freemarker.content-type=text/html
#spring.freemarker.template-loader-path=classpath:/templates  #模板加载路径
#spring.freemarker.suffix= .ftl


#配置Thymeleaf模板参数
#spring.thymeleaf.cache= false
#spring.thymeleaf.mode= HTML5
#spring.thymeleaf.encoding= UTF-8
#spring.thymeleaf.prefix= classpath:/templates/
#spring.thymeleaf.suffix= .html
#spring.thymeleaf.servlet.content-type= text/html


server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.199.202.220:3306/qichebaoxian
    username: user1
    password: 'User123456'

    redis:
      host: 127.0.0.1
      port: 6379

#      thymeleaf:
#        cache: false
#        mode: HTML5
#        encoding: UTF-8
#        prefix: classpath:/templates/
#        suffix: .html
#        servlet:
#          content-type: text/html
#热部署配置
 # devtools:
  #  restart:
  #    enabled: true
  #    exclude: test/**
  freemarker:
    charset: UTF-8
    cache: false
    template-loader-path: classpath:/templates/
    suffix: .ftl
    request-context-attribute: request
    expose-session-attributes: true
    content-type: text/html

mybatis:
  type-aliases-package: com.gaoshu.pojo